apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argo-workflows-minio
    namespace: argo-workflows
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:fDrnRaHchbIUXk5mBLyPs9aKks4=,iv:4D3FE06Qh37dQbLPyFFRGdJ5DkS+59z9DVsDYlWwmgI=,tag:Yvi3Wk5e8VQYXpwo5rNhOg==,type:str]
          stringData:
            accesskey: ENC[AES256_GCM,data:8Zon60uGts2PGUWKlyLmklCPqf0=,iv:WA7X9KgSOSEb9Jq3YH28kdNVU5OyigGz/LVnawEHJU4=,tag:HadlC2yLZX/YxuWfs/nedA==,type:str]
            secretkey: ENC[AES256_GCM,data:aGlkbQWQQv8PfTI5mk1OQM4g4nMSZo7pLbPGQFtowhyBvIMryaMzZA==,iv:Aw2nTbRZECk+/D1TAoO/Cae+WKxX3s1ME1XyHWt0LA8=,tag:E/hXlZJzQJmeMh6OF33Qug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSDFTZ2JqaFFoKzYycEpx
            aWtiUkp6OHRVdERwWnVuSDBFd2pWVjFtcUZNCjhXOXNuR3laRjVMem1keVZsL05r
            bnpDTXoyY3FYMmRLSXlpelN3VVdON2MKLS0tIFNTMUxUM3BvTzQ1OGVaWlVOZVc2
            U0xIOTR0ZFR1elc0bjhVY0JtYkdXcmMKihU5LSEeRiPjNrIjMAbognOsT8trxf5p
            OHOlzQi0mlOnnYAfUZpVV1mSakbP12TNrmGVfqKxneixVvECkUTMOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T18:57:07Z"
    mac: ENC[AES256_GCM,data:b0Jmy07VdIa7ecDojrh5gnKlLiKUVeaaAQk+wZDhX7SLPKcNPlnuEnJZSZSbEWhc9xbCbh9pDSypHJJ/txKzczHIXJcEGJcb44CvRZNXKW5/SZdAAFZhaLdwDYOBUXIE9h9kgcDE9rCGWN4zqRbFYD8ax9jnMdp1th6JOTjfVDY=,iv:T0+bYlquoG9t6/hwKDbgSLnIbioVGxcjUh/BLRdt4J0=,tag:yKlQxBiilYUl0CoX9qMwrw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
