apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: influx-secret
    namespace: influx
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:BiSN1Pw8y1+tN/EgbA==,iv:97W7lSyzlCknIL9su7i1wwFWOSZJH9ePReJF2ZbU6TQ=,tag:s/vkCDB0eC6HzxeI8m5NCQ==,type:str]
          stringData:
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ENC[AES256_GCM,data:clSC2CHei/KYbP/Co2UueYM/HIE=,iv:urojpqoULKWLx8P4swhm0AFbUVMN+U+iW0uO/R5QwdE=,tag:/7yc84tkQ1XqwHkZGQSW1g==,type:str]
            DOCKER_INFLUXDB_INIT_PASSWORD: ENC[AES256_GCM,data:wZZwizskbjJP0mKSJbtZce7LI5I=,iv:iN9jh/gNLTr4bWuzrFJFeNyHGngJ7hNDH+YoUT4K49o=,tag:pma5P7orRn2RTSx5Xg2nzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTjk1R2lPRzZlQldpbnZU
            WG1Ic1BtVG0wd0ZWWmtPQlkydEF2TVA1ckJFClBhckUwaDgwUTBKRWFWbTFPajNK
            OGxxclQyZXJRTUNEQ09oOXliTmxZMFEKLS0tIHJ6Y3dCSi9JWmZORk8xNU81eE0z
            V09adGt5cy9OdVhGUHhBL25JMmh4S3cK5wwg2J+s63m3SFUQvMksJzwLF7Y/nmNa
            lOpPddaE6AMnuAgevk6bffZbhjOgO9wVY+axYcjRlq1LIohddTs4Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T18:57:07Z"
    mac: ENC[AES256_GCM,data:CJUJe7xDo+F2bexJgpVtb+9X0of3IjJh01ji8uV7xZC0Z7ZITnT9P6KArQ80/MbbX381kfvHt3lP21os5ceLndwPTVGpJnMYLihqULx5vFlf6tKLP11JzMvCzaHuDPUJcK4+zAlWfLxkuwiLdV6wikAyWpU2D3eAosqigArm03w=,iv:Mk1wSJUcRpEnk/uTcPDDU0/8XwwO8cvAlOVyQx3E56Q=,tag:076+2QqZXuoKjqnhdFYTug==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
