apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-pat
    namespace: arc-systems
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:hAxAeQMrywQWNA==,iv:qgnY7Oh3garFO2Fx4sSqTl17CBQq4YIGDbuadDJl4Ls=,tag:IUqatUM36d+upZXDQgNNBw==,type:str]
          stringData:
            github_token: ENC[AES256_GCM,data:8c5g0tsKLiqVXNy0IdMbfmrZSvaWo5ORnc689oQWv6u3Mk6veSzUkw==,iv:DI1KXiwX7n9FyRhZoaUHMiC1EDLQTSXx/Hp7zewiLR4=,tag:w34OeDm34uZAocBDtWgxbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITUthUWRIQW1RYlZSc0R6
            eVl5OGg2Z0kyVERhbnNWRUVXeHdmUU1XOUMwCnI0RjlYODJEWCtvdnlLdnZiamsw
            TUlwYkZtQ1FtcEs2TEJROFN4NEJjL3MKLS0tIG0wWStVSXlxR1FiSUFNRXJra0FI
            cmIraGl1VjJ5YzhrenowVGJtMzFDTEkKyHj5RBg/SdXunqNrwfnuVy1PeFcloS+3
            RM2kTkscrCFo3f3yMNqV8tfwor7anfE2jp/QGt61ZtUhSH3m7f0ffg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T15:53:53Z"
    mac: ENC[AES256_GCM,data:QDjU8hEGjSGroatfL5nL0Y9YSnZ992flR72v8zitJcR6ToNv4UWSAja/8b3u6Xss1RYsVldeu4F1ahytnVAmzMvYSIJOItzndO6TfAUkj5YiWTIc/gBk2FM+HpRO4qvPkwIK0+Xh2eqnTaDLvaT7zdEn81pqrkuKhoWmcEmn2xQ=,iv:jPtlW1jNjlAVDLI0EKMI38xRI4yy0VN90qzzK0v/IcE=,tag:Ae3q1d650AHlNZ6Fds30CA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
