apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-secret
    namespace: argocd
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:vuIkER/a3mvd6A==,iv:IODmLA06ACCzfx/vki6052x+5Q00ZTk9/gYZ1QNrnsc=,tag:roLiKSIdiipIw+dvCcv1dA==,type:str]
          labels:
            app.kubernetes.io/name: ENC[AES256_GCM,data:noE4m1Ced8yh,iv:6Mox6QhlzZm2Qq3DGmV27UM1c8oOFeWafe2vkdWXhY8=,tag:aRXGj/ZJMW5AgFqWP9Z3sA==,type:str]
            app.kubernetes.io/part-of: ENC[AES256_GCM,data:03WYxweb,iv:ZQbwWmXSVlxMKrFIPga5vqok4bQJr9PQ8OrYwIrAK8o=,tag:WWY0yHmTTAWtnFg/idC/VQ==,type:str]
          stringData:
            oidc.authentik.clientID: ENC[AES256_GCM,data:ZmoS2sku9tr+dEBUUGelyp99Ix+ALz1NJoynb57LmC9WCVVwcwGKjw==,iv:JRLEyXJQ7llzfbUKHYVaASthQ0PV9zyzL1PIKeq60wc=,tag:SIY4N3YFfOUdEND+ze5obg==,type:str]
            oidc.authentik.clientSecret: ENC[AES256_GCM,data:BBPow+7V9GkVlX8gH16MQVWTvPVClXqH3whxSvmmdfAsQ5FRekeC1kP1uvV81L/0GsGN1Q3oNHMLSMgBnIUd/qqyy3twC2iCTb5l1bWQlvtEQxBHvDyOE4cGLJhUfFBHas9WZP5g7A/1fif60IEiOrBjjpeffEISyxljfBOYiVw=,iv:Lc0aH0sKycg2Mp7oFpb44Q9ahIfoVZvsiEk2ijD0nPk=,tag:l7ZLZQr094S5wBdI46a+kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0elkyU1BYR0o0M2lnWE9n
            YWVYWG1JbUV5WGVLQUVzaGpkOWRVWWFGbkFnCkxXZ3kvYWJoSjhBdDJwUWtwNzVh
            RmJZTWkzS1l4YlZPYm9iODlxanV5b2MKLS0tIC9qald3Q28xL0Y2RUhSOStrMkRO
            NmZFZmdJaDNDckFYdnUyblZBWlBNSFUKo+Z85VQHHan3D6cz46DBiWGjItkSH/Lg
            e++DCD1OQc5dHCu23rjJYqNTn1DqcJv/pnKfnORBboyq+bT07FrmEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T18:57:07Z"
    mac: ENC[AES256_GCM,data:/KS6DgDuRt1FXQVFmVr5Jfju4GzdwzVcS3kt6ANJKt6YTBrXbRnBQr81RrvS+Mi7xq1HR1Y9dsWdSm6YaFArF1h9wuQaolJwvOcgW5gc7llquH0cfuAE2QyyHQeEMdHqkQR5Y7OnNTkkmFZucozFEehLAyOTwSQz5jf/tFU34fA=,iv:7wOmNUZSAzVJDfThJdVvlHv+qEvh8sfDrK1J8DosBXE=,tag:o1lyzuZcSANasNmsQQ7opw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
