apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-pat
    namespace: arc-systems
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:S1YggGxfYHeB9A==,iv:yFzuUhxgmvctTe9mf3G2PKEN5PSg45MlusXL6N7Kq5w=,tag:sYdPch8jh0ZcstXX536hdQ==,type:str]
          stringData:
            github_token: ENC[AES256_GCM,data:bfjJBPBS/xbzHHrnwL+UAiIJYbHxemUFcSe0JEd0WluytVESstUSrQ==,iv:paQ3MmjVRr0cjT1Y6pTBelu8ruOvukA2vvj3TjkY48Q=,tag:dSw+O7rADP3MGpH/cFhDIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdmR0N1gwSUtHd3dJNzB2
            WDlvRWx3cW13ckxKdlRXZnlOcmZ3OWhUYVJVCkgyYWJjV0M3aE9wdWdabkUvSlZQ
            WXZLNFdFVC9RbUJ0elplc1VjYldBUFUKLS0tIGpFTm54L2hleWwvNDVOTC9iQWFn
            VzJ6MFptR0xwQWxUcXBsVUp5Q2kxWTAKg71LULGjWZx7knT8hoFCpN6MBvyVWaV2
            o7rB/ptKdaNoD4jriRGxHPnTLltpOhJd40zyO6M+6BPUwQxQyw0gkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T15:50:31Z"
    mac: ENC[AES256_GCM,data:gHeRtuvwSo19kSt+bBYqBOenBIKUqQytn+dV7qPUTeTTgJeboaIXCmqnbzPvfh6GNxnUfpLPZh2cP5tCfWpJ96StDwpqszhVvAXO8RaGvDInbKWW5QhW564WDcEiHtqXF5Hccza0CvroVbpxvftDl+iB2s4P0pYOTxPQd5iu0ak=,iv:kboci7YG6YbSJJkrTh9JF/rrh9sRTTLWC1gaMWGq2nE=,tag:2hNRJNt+JWgn9Lq8+ahplA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
