apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secret
    namespace: registry
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:ecVqb8QpoJCv2KLp,iv:5456mq5MteY6IysBEe1GsRV1Li3T/PkXVuvSXpfH1Ig=,tag:e1+saPAefyP0RV6DeDZ4iw==,type:str]
          stringData:
            REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:6Nc+Wn8SuuiUlsFovN2/ob2lljs=,iv:M3EbhR404AmA9eubYKiy3QLjDwc9ppvuhsOZLeYMS1s=,tag:ZI6sB+pLvsPXybAxTQH7qA==,type:str]
            REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:qcqbw6VaRKpFNuQj+6OvtDEAIbiIqnuEr41/bRS+NvJ+uM5UA4AnXA==,iv:CNvGdFpIeWB7lHvaEBESQ4ig999/6hSvzcFIKXu+emQ=,tag:JIIgkgAsGS7TcoLvFqUGfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQXAvdXJqQi9WTWdGRi9O
            TS9ZZFdoSDlHTlBzZytvcGlFYndLTC8rSW5BCnpYcURMazc1U3BZUHNlZXVJaDFM
            MXRpZXdIUk1oZm9OTGExcE5jYmE5Z1UKLS0tIHlxNFdzSVRudS9HUE9WYjFCbGZF
            cGU5VmE4NDczM01Cb3ZHYW1YWHhERzAKrinun5poOlsh99ivCtjkiIuTy2cAZawj
            5uReQudD4pE6IJUZIhajHVPiaS6D0KVUcFtSh26UxoUcAj2/cWtX5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T19:52:42Z"
    mac: ENC[AES256_GCM,data:H0H9l3MZvxBo4mnQcWQ3AUuYNqXnkNCEQbJYrq3yZMtO76dMLIa4ENJXBzNTVKI+IDxXW7zs41wGhFPfqKI/kE11vbEZcOT01/sc/LLWd7jvLpLTcsN2u4cxjM+g8QMPkFGpaREu9jjKLHfj0Nx/WpicWXSfJqraew55HMf7la4=,iv:s4pbBxnTfOpoiaxCXE3wZbF1gsJPRXpPboj0o+EWHg4=,tag:+ch/yvE0LOgkSWGyvlKWhg==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
