apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-pat
    namespace: arc-systems
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:2+ozVhQZ71bWZA==,iv:uwpE3Cqclun4txGOo5nrSbL4aVEqY5/OkIhShCCmydo=,tag:4sL2+fl+MbSueIjCHfRhYA==,type:str]
          stringData:
            github_token: ENC[AES256_GCM,data:XF7zn3tk5bq0An1U1AGEuCi5cGpjtj5vnwA/jpLRTxuFqAGgEczdmw==,iv:svK3b3pD5yPDRYRhKGnOPGpHz62/npQbcrefL2ZUGWM=,tag:o33b3DQr6mEfb8rsMVNasg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb3Q5QXo1R0taWEt0M0pE
            NUE3YUthbkFqTjhiRm9KMkJJNnFwclZNblhZCllZR3R5MFhYelRaZFpJeDdqb2V2
            ZzhXY0RQbHNrMTFyWFJvUVlhZ2tSaDAKLS0tIFQ1aytKaE9lMmNINmlGWDl1a1cr
            ZjhlbnB0UzhCdXZ6WGRPamVpdUtxb1UKjRudsmlxDgBuE9I0OhNOQXOG2IXqdOgc
            u1FY8d+rjyCp8lGA8EfHCQdh+k5C4WCzN5+kf9o0SGsqG3AGJBgw4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T18:57:07Z"
    mac: ENC[AES256_GCM,data:vGtdm8rQ//i87rfKgo3hjHGkIHCMJcjt1Bdylok08QezhiQ4BR1NzmvNaq2fG1u77PEMmXmnifhULGQDC/ZrgBWRi3NawVIb0AQUt+Cuqjiqfa8GbxtbWqvBNRyDuhNBBItsqhPJJTSd+2xGzdRq8zfnT5337Td/4Gtf+QSbN5w=,iv:4e7aOQ2zPAhI2Jeb1LYHsb0/74qLobThx9evaoz/LU0=,tag:l0aZOsFugfhkiNa3j27z8w==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
