apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pizza-secret
    namespace: default
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:Wd5uwXDR,iv:T7ueijPYgDxfy5DDEzOan+g/3+MozVTiDl+mWbm+mbg=,tag:+Pr/xUmyCymjVRsFXMZ12Q==,type:str]
          stringData:
            bb_api_key: ENC[AES256_GCM,data:H3Fso8xnIXThj7Z9FR7hppDs59upbWogtVfwy846QjrICs41ptjK4g==,iv:4G1ywdMvya59zrjiOhKmORx7HnF4zAY9lbjk6EFglCc=,tag:n4v1IgLRY1fUbD1bP1iL+w==,type:str]
            bucket_name: ENC[AES256_GCM,data:wxUk49NCMQ5guls=,iv:NJD6P2BRg+CeMZA8JrSaNcBalUwxFbUtxwtVaABWIso=,tag:Rho8GaILA+zJ17EFx9UUkw==,type:str]
            mongo_host: ENC[AES256_GCM,data:UFY/pJhvmxD+wltpW/k=,iv:YhS1demvkzppq+B4fcvzuY8Qeg6cAvHjCbF/PU4o7eA=,tag:sO9yOvuORYuxPlg9x9M7AQ==,type:str]
            mongo_username: ENC[AES256_GCM,data:PFduRQ==,iv:k32JstsDu6yK8VU5Hv5PLbZ46uG75vG1k6m6tFmYx0U=,tag:lKuO2jxMJeY4GWE9CmcPZw==,type:str]
            camera_url: ENC[AES256_GCM,data:+b8SOEzH78WBraKbGXJWq4rpzIbqb8RvDAA=,iv:iVq/6DmSrVesuJDvIAxwnHVtaM8VI61Clbef+oMzA1U=,tag:2pvLRMmiWiRbd14SdxwHyg==,type:str]
            jwt_secret: ENC[AES256_GCM,data:P+i+J0G4OF4/TwNVMuvLD3PinN1zsUEvAFyAEUiyEhfXw4hX9RxkdnVU2Nr5LkDR5joBzSvcYjD8az+GtGpIOw==,iv:1itOJb4z/QB77/UaR+QVZkG0wXlgkKJkBmi/6RD9wa8=,tag:HXAVShqOri439FiULNHFLw==,type:str]
            secret_key: ENC[AES256_GCM,data:UIQ28id0PGQQi57Sya5+Oyd0/iSyTfUqKyekTGvJFqS9IWAhjkm3WQ==,iv:JLmg7GL7io90Uh1eAOyn5VwXsjHjuTu7L6uNWkmqvuU=,tag:7DaMxMewyQNF79cqSbbiwQ==,type:str]
            thingsboard_jwt_token: ENC[AES256_GCM,data:vrUwa0M4ntUEdbx9x7aag/vnzT0MH8Wpq+kjiEbgGXW7uSaBe3aDTQdxa+LUCi46pl2DWW2tX/RqEcoklZ+FQVakxrKvCXZCi4Sw3wJHznzj7xH/QUDztMAgc8dTa3cj2ST7mE0REVOKQEYPB6aE5j5L94qKlRgheye065MGB4+rhobCHlO52bBXsE2CrYscZF6aObJLqMTlFgypW9rbn4PADWeXADlRtz+RQO/noEqbB4M6lSTMRuEMEyAy5sFpSFNaGMi+btctvBEIw6e0gBgOlcKXf4agYG57PPPNVDbHm3fA7sbuqCm6zEZRlBQvUXYPimLBDeCX6bUdoIsbSo2mFWOIHguJWnAcgzIx9FvlqGyeNoqQ6y07vrqr7Ui9Pig+6HRMVX/2eiBIqZDPnO7fGl7fPb1/q2/R5aFe3gF7cGKcue4+L07Ja+gOf4nItoGCGVlIWUu2XushlOT4tdExtAiVNshdIL1YGO6l6d5BlsqbzL/WeRhX9CMzhcfbOvjIJdALyJVjHLSipzDnXH6uIkoNzjk2vhUF864l9gPwWPWFhXWfVSB8liNcMqBB5NAPMJyGVdqB0n/61sbd2UJmj00O6sur1cZ14i4PMFWf7QvO0U2/92/qiA882tx71h9FQpbzDKjRFA3Qcbp8Fc/okK41jGFog5AMspMd7f3hp/WmkeoGqXCLIxiBRD77LuWMWSAE57TRP7Isdj5li6I7Dq44hPWvRTTt3Q1SuNkI51jQIkBq60jADhrD11X9J8uYxt+oNzyG5Fklg0QDoAhgPe2jq/1E183qwtb9LtCkDgNYTN4U2No5WHclZCQLcghT,iv:p4uwLAOwYi4paCxACOUerzRn4mbQpMp+QGqE2fnTvmg=,tag:1kAPdOAEbiSV8Bvbkkibwg==,type:str]
            access_key: ENC[AES256_GCM,data:hohtBj9r0oNO9AF/spPSr7Xhis0=,iv:w0I4iS417rX10bdbRAF1jv8NsEW4wWdyki7w5NAea+Y=,tag:GU0J2NwasOWBh0lhxy8Z+w==,type:str]
            minio_url: ENC[AES256_GCM,data:mpU9ElZ59kj3k8W/Gw+Kt5Zh,iv:P5As3xsvGZuSxZXSNZIcTzPmz1vFara+JIGuW+SLk2w=,tag:MGavw6PbybH7lNd9YgMnvQ==,type:str]
            mongo_port: ENC[AES256_GCM,data:zpcKpVA=,iv:BOKsWCGDpfTSIJEoU3yTiS/PzelsOehKmyIhNZZuVCc=,tag:RsqXjmX97A6ITvUwKkgb2A==,type:str]
            mongo_password: ENC[AES256_GCM,data:nZ0p5lRZ,iv:HLqxTtbtgcuN9CEgxyoM2dNXGg5srCBDoTZmt0kXcHg=,tag:LOJZSJDu8XY3wlg29ouu1A==,type:str]
            bb_url: ENC[AES256_GCM,data:Ck1wCh7ndEGB+n5zBkfXIpZOAmdfi7hGIQaGRyv+2fQtDcBKyw==,iv:tPCGmaueETvD6KY2q7SxxaZ/W1lWOdcC+WWG3Gbnxqc=,tag:I2LsGfJdtbHSaxj0k6MWRA==,type:str]
            mongo_database_name: ENC[AES256_GCM,data:ZRxG3lbZmGE=,iv:fxVESkDPLYdLGDxFMcxPcQwwwLNQxjT423XjcxeM2I4=,tag:ywM/ZEWamD1klzVLaSrPLQ==,type:str]
sops:
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U1FSU3h5dE1zZElXbHlV
            UEVUOGJTS0NyRTRQSmR6V0ErbjRtS3c5MkVJCk9ZTXdhdk1rRnAzek5hVkNPa3ZL
            dUorRVdpVENFVXFyMks0U1lWekE3UTAKLS0tIEorbHNFcEdMeERmL1lhMk1wVzhy
            UnV5KytlTVVXc2kxOFpUcmI3VDg5K3MK7IH3zx+BXmJ+hWKgfwpygGeuxspMsOfH
            h7+yf8mccnpwVMY75NEybt99/07306Okj2do8OBRJuk1lz1QhikxlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T15:53:24Z"
    mac: ENC[AES256_GCM,data:EwRuwyDzpuputJjusqswFC6JrNQJUonDdlqAeZQ0TfS2nE0Vmgf6EqCZJU9T65OZwsc8FhWDv1Y4PrxNymXTZlZcZP36+3D0Mtd0+cphonko7qxkGSEaKk4UhD2LAxfaEkgIfIHHeVwcAKqhBQaz5lNSAcfkFTiHWMF1NETkShY=,iv:9fmGXDHbqMBxpsoYANICEiWJfbh4V/6wnxYXEw/gA4k=,tag:aFGrxFXkbeeiLznfUlb9sQ==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
