apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-secret
    namespace: argocd
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:t2BRo7iTWC01bQ==,iv:ItpPzEOVwGxpmrh1/pvMrthJ2o5oO+7Zzg+m/uh2/Wc=,tag:P0W0gzYeHDL/4a8h1otTZw==,type:str]
          labels:
            app.kubernetes.io/name: ENC[AES256_GCM,data:z+cH1DQBBuZA,iv:wawgZNZI+61aduqEkAGaRWy50DpDXP1BuHYrimPzWQc=,tag:sJM3uce/dE9bkcX5ESYEbw==,type:str]
            app.kubernetes.io/part-of: ENC[AES256_GCM,data:miP0e++U,iv:/9JszKnQMWYJVAi7R4Q9Rm5F1y52x85dRkyrKiBX7xo=,tag:NNcthyWX3XGWgLDh1Xj/5w==,type:str]
          stringData:
            oidc.authentik.clientID: ENC[AES256_GCM,data:eEIyTIcPgybQ3k2F5TpWKDbMtuz+JmsgX5WVZGDSZZY+sKYI6LKbsA==,iv:KvgDyJyld8G/6nAsVDKrzdEiC7g/Lf1eRSZgqdTBXHA=,tag:KFH39M7knOP0D0h/RvzgFw==,type:str]
            oidc.authentik.clientSecret: ENC[AES256_GCM,data:s2lumh0GIbVSHGqH0CaGWW40gX4Q3LnEbiCwE4GzvkscS7M1ZxYbianI+UjQ1V4QvM4OtvBmkgC0O0tZgRQQjabpWmFKSZgp3l4uNxLxLjOOp7yKsie6hnqwNaGPdhWFqtoQYq8nki5OOLjZ0ha198OZGWh7r6upQRwokAiBWxs=,iv:VIj5auUs7s11lh40lbYTdS3USjiFCf/QQaiSPjTC59s=,tag:JtGKXI9m0Yo2BY3MikQv4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR0cvTHdNWThxanlBejZ2
            OVZxSnNlS1ZnY1U3YUgvdGVxU01Bb1dtQ0QwCkU2WVE3ejlWTDBDVjd3NjQxbThH
            U0dmbGxySFU2RnlxKzRJMmtFMWhzN28KLS0tIFBVMDBUVzI2SmxlZW1tbERreE1Z
            dmxZWEQ4YUxOclNwTHJTcEVCYnM4QU0K4o7JdMewwl8DUXZXLRkD7J067pWR4ba9
            c4j0c2uHczi0SeeJrLSS0sYnPonLC9ocQvKDojDplI1uxeNUiQKllA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:29:00Z"
    mac: ENC[AES256_GCM,data:ZX6Fl7vz90usNnKhEaKNlrA+vZnhjwyxRJn3biYQMjAZKjnNZeFZ3p3aSJmkomcrtHn5cC9dEG6DjJW+E3+v5/YtIEewa+OzwRUzYQtsAopf/VgQuaa/uzlENaDC7SZTP0gKIcgu/h/duxOOUEjMTFH/n/F3dGKKPFGGc2cW178=,iv:KP8CAgyaRBXzcSJDGmCQmSrFt0eYE4Bdw+QlpizC5f4=,tag:5YURmflGsGNgC6jfKFXEZw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
