apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secret
    namespace: registry
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:8O5tuQcOShhbmXT2,iv:FeCfwpMoovMh87Q0tYiyj20Mh9dZnHgZqfb+g01C35g=,tag:m4gnWp3eOIwoxwpz9iVmrg==,type:str]
          stringData:
            REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:VBghZXhHL+jzMExlxnujZkQMGa8=,iv:BBFvjy0h9/dtWdD3YpadURQSGpkmUE1Wtn/F/TtU9ak=,tag:+YgWSDSQx17OXZiZJpsoeg==,type:str]
            REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:Z5p2XZ6Rz6uzRypMq/U74hvTQm4kcP/LVMwo++B3AuMPgIYF65He/g==,iv:FE+BCjd1BMSWfRGuF99j6VRJCholz+oEuCO/J1Y2P1w=,tag:an6VZIMGfRsaEHHkkZFWLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYXBDMkVzeEkwRFpaZHFR
            U1ArRXJ5MlY2RHgyUzlRYi91WnZHZHk3OUVRCmczZDBmek9yanlxbGdjdS9BZEJt
            T3JScTdTRHBHakU2RjFhbHNxR0tUQ3cKLS0tIGY2TGQrZWNNOVA1bkljdFVLQ2sx
            V0NjVHRQQ0wvQlBkcmc5VjM3a2Q1THMKLiqT4FidXIMTP45tuSrVd8tA+om3Dx7Q
            8nPnMI6stRipCpSIKwNXqx8gaQFKXtG7tJrGGUqCLRuHBAVcJ6bl1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T18:57:07Z"
    mac: ENC[AES256_GCM,data:6Fd1OHkMCfPHBUrZCNu1ekVVw74tGlsX/CLjggFcvr6XZPqAPlB5rbZYklD+b1f+YOnXHNmrF9FaJLcPkxn++3QGtvQqPgH2cwaEfLAUBDZh58+IaDmBsg7mxEy0G0cPdyN/06UkjrxhtrBjhKYyehQhtL2yv1Z62ITygaXRkBM=,iv:FvXqWV5TKvucwvfAHX37fXwLw/3uNKWcKmzsGDlARnQ=,tag:LkXRjGgV7qN9pE0ve9QMIA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
