apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argo-postgres-config
    namespace: argo-workflows
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:h8RXeB0e/OYVBjHqk2Tq6QDJamA=,iv:9DRR3AW6ezroiuwj86KeYCndCJjfJoPlb/HgMkNghVQ=,tag:2RD9bLKfHAKKW8KdddekTQ==,type:str]
          stringData:
            username: ENC[AES256_GCM,data:xP41bWrbIyI=,iv:4OxlSDJDMHn8oSA2Em7Ugz2KWdBqc+fLrAoCvNE3cHo=,tag:1GeYOhBnOsjbvIijZAqMJg==,type:str]
            password: ENC[AES256_GCM,data:KPg4iwifCDb2991uoNBtbnMQCCA=,iv:MZrfOMNCbPa1Sj5vszUay96oeMEm97cI/b//Xzx3+PM=,tag:JH02v8WMX16nq+kvEC7EcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZFd0MDF1U1dPUGw2TlRX
            b1NtOHBEKzJRMXdXY1ZnU1RoQTZjaFF6Wng4Ck5aWk9PSzNxYmUwaTM1aGdVUElH
            M3VDWGFTN25hbGhnSWNqdEp1OE1DTFUKLS0tIEF3QzJKMDFzQ0hVOGx3b0VkdHBH
            blg4TXFZeUR1bTRlVG9pNkpTNGlxVDgKkncbhPXRcbs6tLFq4TsS5gJPTX0y7p+3
            3jfOF4m7mFx4+kMjIHRVqddgt6m8CkJRcKsPeCBvHYfblkb4dTnLow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T18:57:07Z"
    mac: ENC[AES256_GCM,data:fif16hAUoFdJzcl6RQfYPqVq+vo98S0qCaxK07STStggj/4LJxHnDacy5ZbTmzuPTvVkqXRwPb6FPsJwH6bIpEahOR0VBoMW/1YArvDm0dmNn8zl+8eSgYrNeQ4wRTCoMclc9YWILAVNS2kY6dFXjzlTCUaZwrK7fOpbhZfPVaU=,iv:LK88G08XONowM7l9DtXg4aP7ArvHq88PngHudgZ0w2o=,tag:mXUfkKZuZFi/aSYQQ/ffUw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
