apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secret
    namespace: minio
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:CKiGfyiqIywZzh7q,iv:cxwXZHJ3M9IDVBvKhD5/z0BTrqceQoojXuocfHz3hiw=,tag:n/rYL1gpxIm8/9/9qn8VEw==,type:str]
          stringData:
            clientId: ENC[AES256_GCM,data:Fc4drR2/oiCMG0TKU29BNbglA7AfOl7H77iG/m+mFohDvOC6ZfFltw==,iv:EB4LrzMz9+Rd+MB0+yioLLWL2OO4kVxrzIht0BvccV8=,tag:ZLZkTxJ02fyVxO4WBZSCiw==,type:str]
            clientSecret: ENC[AES256_GCM,data:eJCcYgR1lVUHhBAZNCS4mGi0lGzyW5gtgRxG1foWFy9gIAvMt9OoTOIgM9iajbX9D5FpBmMRIYuCBmyYI+sLURozzPCZdHncEDAP/TJaGa2fy3EhnyvCl4BcI/0kZkDuFYC5+ZgF6HnMPshss04WeWzE/h0GsN/IeknxUMaqQj0=,iv:mDnBHsw3oAgwmV8hn7HwZy7Y2BhXYSmaTaGu3WZ46+A=,tag:MhY7RSIR/xrEg+PorX0APQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheDQ2dUFDREl4MFZ0dENp
            d0lsVVRpL1N3dlIzNmVCY2N3WVZFb3lvSVVrCkNMNWpWWFc3Q1YrdG1SaldZUHZE
            MWJjQWEvM2ZhSnlMQ3E4Qkk2L2VxRzAKLS0tICtOVExWNGN5d09kZ2lMUk9QelFB
            TkdOOGNIN3U0d203N3dnZTZSQ1pqbXMKOzwRHtS02w8s/gaDoppeaWnmax2O7nXU
            UUHcsHcaQ8/IWb+vQ3NDuc8Ug2aFuESf/yKUKgK6eriarojU5b7tEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:29:01Z"
    mac: ENC[AES256_GCM,data:1eFi68v3XRXOnr+DAAmYvFUVl8IxG3pye9apxOa7fIWHe8F+orLuhHfL3lMgN8y9KU4MEbmtU0XbO6V/jks32W6PNw+luhhGIRor13h6he8uwkJxsLtpuZVcsVdDlZWXbxbGkfjhL/bEr7Spkqj2cfKTyBifI757uTqB1NT2I88=,iv:zjcTZYwUGzl9KxXU72AEeX3EjR6i8lRVayeKTAk0bKk=,tag:xem6XiK3CsbH9wV7J3Ifbg==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
