apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-secret
    namespace: grafana
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:vvkQYExtD5XQLedfhxQedD2VIIoRpnO3RQ==,iv:4I4pspJA0PLUmylH69qedLE69jMqXAk00MuiWxBVbTU=,tag:x8HhyvPFIZ2/kCKet3aZLA==,type:str]
          stringData:
            client_id: ENC[AES256_GCM,data:t5KTQx/gfAeFNjCKytgBVqkRu60WuboYXHhTIgNU2TRlrjGDNJw+dA==,iv:yf33gt1DgVPVjexfv6Kp49I40773Z/Ut1JdPp+1XR10=,tag:1p7ngPp46U6KyW9p8awM4g==,type:str]
            client_secret: ENC[AES256_GCM,data:qyMWAzBUJqHNYZwlxGt9nT1JDhQoStkuACbxiGTavnRjeyfnMUV6iGUQM6eHB657befjLZFXm8zcCSP4oJvN79S/9LZwtT/gqJ9DUWI4cI+Vo0EmlMDLE7RIE7nc10rSV2U2sPXn37oXIpoettS4x0vKKnp7DarP23/BX75j70c=,iv:EcdPiSQvbHdAbT961rJ1KWlJfLflLs6GzvdJgDSTDso=,tag:/W9phePmqzvRH7WpG1tVdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SkZaVm9wUWtEd2Z1bE5v
            Wnk4b1dLcmEyYm5vWnNyRGVXOWV6RWhVTjFrCkMwWkhKcnFyeTlrcnF4SkZ4MXNt
            K01MeGlWbkRDaTdZTFN2amp5Mi9GalEKLS0tIC9wcFpTSkp2OHA2VjJQUlVNYnMx
            WFdlWGRTdTZoWFhLb0crNVR4alFjWEkKm5CdMAnyXhBd1XHL+gook1RQlNdfgt6B
            B3u59hfQ3TRnNo089fCHSdEENa/iknrMltn48J4PXPpEFJsLBq77vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:09:38Z"
    mac: ENC[AES256_GCM,data:5LzZToM8U4+1mSk8iwMEBHLb7m2uxF/7Q1d/AnDDkP1RAfdHFOAo3YWhj9OBSWsOHrUS6qD8LipIe0Jy1hy+j6O3g4GH3nSFKmaR2QRdf4xjTnFCs7a7UzTna2CKxzZKaVfXSo+bsYrmnkcfX3zF9xRfSl+Q7iEDSUJge+YS1+Y=,iv:bJybtmn0H4jWKzQlOH8eZlRJXSnWdvS64P2mx4e2UPA=,tag:o0IX9bmr+/062KdaJ6LMww==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
