apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argo-workflows-minio
    namespace: argo-workflows
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:VeZQbdiXPXo/3kpETGokpqx8f4I=,iv:bY5MoUtDUEsbGlr8MYPyh8PMjOBxZEBIDWyErUwEi38=,tag:HvxIiclrbpdTAXKGNGJQ3A==,type:str]
          stringData:
            accesskey: ENC[AES256_GCM,data:WYZ3npYJpe80rjm8hWSAowxBvn8=,iv:li53pYBFe0tH03NRMIt8N/MEZWd+N6qOeF41uWyOTGw=,tag:GvLib3V/7y9LG3Lo4sWrPg==,type:str]
            secretkey: ENC[AES256_GCM,data:0cA+YxvbcMAlAamTUwCsgbimsVs3HjbSHOL8c7o6NaAkaTsp/YhO3g==,iv:gxidO1FSWpjFDJd9s0YdgC3I2O47RB2+cL8NAqc7Fpk=,tag:191O9jSJBRpTw5xDyA8/mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMXlvTFpJTDVyVGUzd0dr
            QkhmT1doT3I2dEV3Q1pmWUd3NVdMeitTeENNCkE4ZURyLzlYOFFpNVBCSUtCVVZR
            djViNUVialdTYVhBNllrR0JzUzR5dU0KLS0tIEFGMG9hdnQ4clB1eTdCZkJFWDFQ
            SHhPd1FoY0JMRnpKMUw1aXpkVVF6YlkKlLetrFggJbI8MeGDhj7M02NbyeR3r1Wc
            rM1VVbXQykwyF3zahZMfmd3suE6Hucd96dtPMzukJcEZoLF5uaXhjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:29:00Z"
    mac: ENC[AES256_GCM,data:OryYDuIR3nHpGUMAPcE4H+rQIbBI2+MBO3Q2NFVjN/Ppbsqtftd+cUO6dvyh7+Fj+Hd6qEjqxOoEyfevGqNutIYVqYfWQ/DbAyapxl7QKd2yYRa+YGlCdhXue3vQskTE5Zd+7pRLMoq+PBBt6K5entPtbO1T9LVt6i2FxGTZfiw=,iv:+CmMx/fQgKD/1Ttf84PpQFwGBeMPkv58tej/yii7D5k=,tag:Na2NukLCSF2R40Wn3S+LfQ==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
