apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-secret
    namespace: grafana
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:t41temdMzU/oTnhN1bkEq7WLaxrhWNWSlw==,iv:XTYaPhFzkZNUE4X5AenNFyXNGaJdmUALeQb2gIWYfIg=,tag:0SIZqASlx/gbJxDmoQr6pA==,type:str]
          stringData:
            client_id: ENC[AES256_GCM,data:WpH82GydpV0a9vAoOOi+7gVQVKBOXe6/Ti8jpFwalzHbyhKim8f8NA==,iv:MPYBMb1lEuIOnnKCHopyfbYdVOzcxKro6PyQq5ohQTo=,tag:WELjwoJCj+rMb6QVoqllEg==,type:str]
            client_secret: ENC[AES256_GCM,data:yDMZ7fw12e+cbktN9IGmnsJ2sC0jBggQ9+HLudQ9qK8hjbzOImfDTuCxOnmLCnaB7PYpLm377/ceV/rBCMzK13bQKIXdbizP6Gz6COP2RbvFlKWO6eThu/G9yCK2E69d+hxXfQ8JIwmY56WEbx7D69tossggip7v+0T8RGxFwuY=,iv:DPb3bGnK0/dyZ77xZEau8DhoMObxmSNXKrMvjJKQMks=,tag:R4RqlpA6G4hswGGZ3qzHaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MDcrb09EeXQ4aWovMlFp
            V2czQ2V1andjNkJqaWFIZkNyN1lMVGZ2N0IwCnVYcnNoS1U3UzBTeWlReW5oVmVL
            WHNPSFI0L3lkc05CSG9aYllMbkUzQ0EKLS0tIDRwYStUaEN6WGxGUSt2aDhMcFFu
            K04xMndabnpyaXg3S1h6Z2l5QVNnSWsKPJ12RywSCHiN4KEzhb8bLvAbZXvwB4L1
            lW0yF2Mu4wx2eNbKmYmUpRdOWu8q0n0zt0j0TNQGvIKUrNaeW6CilA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:29:00Z"
    mac: ENC[AES256_GCM,data:WdUb60oma8zdXJGJ0uDLPg6cvsynmzWHJILcBt4n0d5c1gvrzBpArD575P69JDVHZs/zibppTxPLveJRzcBYIjorw8M9tqlmo8Alxx9WvKvleEYocr8AmCFN1m8nyKu6AwkzN8cRHXOB5I6AMS03UC34shs4frNhdtrpcAx2mNc=,iv:EgF9QCoquMTbLvOUl5sQLe8LhKE60MZOmcxLWpLB+mU=,tag:4ZrqMe1X20JV7uaQGMcPJQ==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
