apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secret
    namespace: minio
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:Mc8InDIUin/qOhAX,iv:Su0TJXW/rGjNcLU9evawa1A1jBszWoTUQkWc1YMQWwg=,tag:3hEJY5NbH+P5QDv5gK8KIQ==,type:str]
          stringData:
            clientId: ENC[AES256_GCM,data:z8N+IfqNxysnXQd0ooqiEbMBOpzvJVTll/ff21EApYEbrfqh9GbS1A==,iv:La6OP6HbOb5kkWMZNmyGfxAIM+GfaYID6uu4dFQOc9w=,tag:ca51C96OcReA6W+E7eCI3g==,type:str]
            clientSecret: ENC[AES256_GCM,data:LHwVaOfJ2DmIeH/tTOzZPOWFpVKqF5JS0H4v4kKB+fh1tktzbsidvNFslUlHGHxs1FvKizv9GfcylIrdWA0kN84Jhe4Sdn/YfMUyJYafz59wF1RzgYIHgCzxf4NAcqikypBnfcwJ27mjObRJF9Wt3Le5qX4ZOoqcG6qe63CuzX8=,iv:sQfsLA17LF5/n8k7P+o9N7PPovIbLIoFAJXlFFrEJ+c=,tag:r369+g5buZtpYPmuHO3AVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS3RINGltTDk4S2VsUktr
            LzByNTMrTVVSR0J2R3N4UTZGNVJjRkNBeFJZCnVIaWFQTTZLNmlQbFdYbzZIT25u
            RndnT24wMHJYajBUSkZNYkZ0MUpYZGsKLS0tIGx6eHBjVWRUVGJVS0p0bVM5cU4x
            UExZNUVqbW1zN08zVGRRU2dTMXREU2sKuZNCzYcIz7eCzWmNOe3w5ACL5Glw0UIm
            anOHplwgdswNJf8vTJg2oZQnnUevMNn5iDC82k181MHaCVpQIv0ijQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T18:57:07Z"
    mac: ENC[AES256_GCM,data:rZnlLs7Xc+/NcG2sw9Q2bpMLhMtg16FyBr0HJl733Rv2jELPKddm8i5EuhxngvU8YQutj0e0je8FY+NcwiC0X04JvTQ+0MpdTm4H5kzgZklvgt3TSBqDKLHWXeLx+51m2nTDHkDWlW4jM0LoiMYu7DUBbIyOsUGB36AibB8JAoM=,iv:jenu+sBHXJ9GRE17ltBvPhCIfneV0Iq7q9iLPyWFIHg=,tag:hcVnZ6muk/DUZfeIf8H2OA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
