apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-pat
    namespace: arc-systems
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:g5WblWSa4TjySg==,iv:JS/lMTdVFLBXwPBFKxnvAjEcgPJSCnIXhI3hAK5UIz4=,tag:CrjSR/flCCeD33x65DrSGg==,type:str]
          stringData:
            github_token: ENC[AES256_GCM,data:/HxBxNO5uQpQUxzuUqqzjY7m3xX2sn9I0Vjw+pGnCwdD2UVqZfxtpg==,iv:VoTiQxYHz4FKW/38hC1UHzbB6o0Cb1I0g0GdbEDNapc=,tag:J3c02fx2lcifwQ/kBNeBkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOXpVdVNseFo0V21uWUdW
            UEtjbHpoaTA1alE4ZVF4KzYzVDdKYWhhd21NCjRXWkMyQitSNmJnUHJVY0RQYUdy
            VGZCa1h0Ni94RGk4cVRxanZlRXJFZk0KLS0tIDJ3ZU9PRmVmVXFuamJwNTVDUDl3
            SlNXV3JGYk13dExNZTNVcmVmeEJxa00K+Rv0aA/xKc6Zb2PjQA/oOyICEgWtZ4io
            x/8f3OGf/5VwJYCZAAuUpRyLxBYiRDBPlklu42H9564ct/YLHlWteg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:09:38Z"
    mac: ENC[AES256_GCM,data:Hjqp3Hto2DlqT7jxZeBUXQvr3A57UmrtLQIQt9mJSFuVqeJB4/07dep88mG89i9B06hxa6N33AIwGlcuh+x5lqIi9YyENMgyhefGEujLNG0B99ptWGpfzITuVPn/t3HwIa4MuqSEawG7t+At9Z8LgeVyGxyJuEzycFm/0LzkQ+k=,iv:2HqMEQUs03RDCZrx7qQkU1MD/e+UIGKhKZh3c5CtDnY=,tag:fEmth6sDfTdVliWJr2IEeA==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
