apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: influx-secret
    namespace: influx
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:5uXix4bN2mk0iXDQqg==,iv:AFt03gDp/gbZCcLKfNppeoo+zgvTSRNkdl28Rhp5OIk=,tag:x1oWzsEPahNGnel0Hr0WZA==,type:str]
          stringData:
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ENC[AES256_GCM,data:iR5ALouDoE3CzYzQMK4j2P/jP64=,iv:CW+BtL+sZOadCEn3PY4NI6qUCM/Ypd108+TqPJk9SYY=,tag:+4R3T8ddxhZEVAmDKykduw==,type:str]
            DOCKER_INFLUXDB_INIT_PASSWORD: ENC[AES256_GCM,data:jFzEn5mrbnnqH9oCcQPQAykNfi4=,iv:NBfih9cVuT6fzWsg5Gitox1TM0QGp2yNUBKuvHmzMZM=,tag:kiuB5kkRO6z9Ni1uh1jWIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdWUySGpDSTNVUk9WNU1x
            dXl1SDdLOUZ1UjNjQjR4OUlncUdwWkFJYVRBCmZhOXBycWlaNjBtVEQwRTVjektE
            Z1JTYkM1VlpiVHdJZTg0ekZDSld1RXMKLS0tIEllamFHaDBtRU1SZVI3RkxoOXY5
            S01lV1lnSEtRSkxYaVgvcC8xcjB6eVUKMykLvyyPLglQTzK84BQDX6KZbAgFF1al
            OJAUHnD/tjcXt79uHEm8oO9dJ73N/z0MnPHnYn7ConLdgtF3XNWz/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:29:00Z"
    mac: ENC[AES256_GCM,data:wQcR4IB46JaY0Xes9UKAy4dtcOdd58ZbfY9Lozuwd6aerNN58fjXQJxWF9P1r4ZG1TsmEvztN1Cf9fgVvmy5R1riqtvBZUQ9YvHAQCCmtbSmlvNORM50+a8oYsaPglg0C00quXcDryd+YAfohhMGT2oEcjwaEMg2FoOom4SStiY=,iv:zevDfpWtvlKFdOWViecItR6rxMlGy/4nG2nGq/ZpebY=,tag:v73HLPNco7MYAn/9vjR1tg==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
