apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pizza-secret
    namespace: default
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:d9TPoUNkfFpVgtnJ,iv:GhdWD4wyDvEEebDBBWO2SjBVYc3SeS5u8W7hr7qvFeQ=,tag:9dkLymJcPMfAetQAzQfq3g==,type:str]
          stringData:
            bb_api_key: ENC[AES256_GCM,data:kZC1X+uRe9hgBgVuWzz/SedrLV/HphM2VbULVmquTrp8fCZziN7hnQ==,iv:nerU3+6unjVZkRqkV8lSNQ3lqW7s3pp2UxgLv+u8GJQ=,tag:/JgvXKPJ1LkUL4sV8UrfuQ==,type:str]
            bucket_name: ENC[AES256_GCM,data:c5XwAtUmibejoI4=,iv:6CTQAekeSBDICQjaN3LMYzFb3cpDkwawuHOEMwZe6n0=,tag:aLnw+Q24z0SNNnkuSF3o3g==,type:str]
            mongo_host: ENC[AES256_GCM,data:zInfoE8qA78HbMCZ7us=,iv:7a1yWy2rMRYfePcl4Gl012LW/haO8Ix5td9LHvqNzuo=,tag:v2+fFOZarEa9wW6u+7cLlw==,type:str]
            mongo_username: ENC[AES256_GCM,data:ZvQo0g==,iv:RrPQFSuHjxR4RjO7cqaNztVduAHVHkUdwGlehuuinUQ=,tag:h/i/rJPMvfLKdZ51d68Jpg==,type:str]
            camera_url: ENC[AES256_GCM,data:ccYmDtcbE0e0TS9hL58WzBM5hX0fMmBeFCg=,iv:2K9/P3fCI0EdexpjGeox1a5FSqDGTnUSq3kk14eZduo=,tag:vsuYwwGkpWF37+ZpO1wUtw==,type:str]
            jwt_secret: ENC[AES256_GCM,data:2vnBc4ZpUs8uvicL6uDbaYw3IhjuNXvmliMPTE9ukiHiLColGqREqhVLJmMG64CBv3y7TLuqAgXZ9EB3ERPvYw==,iv:D+U0BhYivEGc/xgvzVnw4uLzIOIARVjsUU+fS25tjxw=,tag:441rVJw4+xY6P3OnadFPdQ==,type:str]
            secret_key: ENC[AES256_GCM,data:5OzKgM+evZwrOrTse/JyHKj879OfXlkzdqZliNrr6LGrgtuJwA2WxA==,iv:cjhOLb2uY8SMYgZ3VBa3yqxkh8jyv9bIazIE3s2dPtw=,tag:xn0I9//pCAvQrc7i5Syp1A==,type:str]
            thingsboard_jwt_token: ENC[AES256_GCM,data:eXkJBoABV2T9s+CB1pVAoG2n6gluwqvNWf+E9WO9bCmng4aG2gsAhfN9EZ0PDxMGu5LjXEGTYUv8mevsCpUbU9CwKdP+2bDAmacEVtzklmtK9m0LYNxeOBDiRBEStKie16Bj0kIAdt1QR/sBkeMNjeXdIkX1/kWQgl+1n8TOIrsQ+CWxFKKIGa6EB6IKvJGlkYNd4LaYQ5PoeY7d3ei9I/mPaTDv+jjuKTRnvKMT7AN/DKIqjZTudzcPh1UFB+acjfHKYAIkf1ukon7I5Z61c2XIjVMR6Q2XVOQBFxRlGaCw1zfVNwL7gPSZXviebvu9BZpOAq1T3BLx2lHdnmj5hwbfhZVa3Cg9qdIdmqCXHYwBACRow79TWnnrH77e+eX8J4GaCRekriI9cJ13gC9RT9nXSTGZ2y2nzebfYrOaPDyKOGCZBocJHWIsiBquZZmAXqcYP27kCugr2qHBt9Zaxg2iXr5hdwqDssYvE0xKVeRRmGWB1UcZeq9KPbc4qJvghyC4HwnTYcnFlU0GRB4UPyOOkiAtyiFRtD5hdm+PKUFOXUpBE7N2av+YpUGE5SkEYxssbRlGRyE+zqXFSiAMcNvxTU7oRBaq6SyyBV2pTddFxWE6ocf0hK4fieR6ANbtPnH0Vl5CB4v2ZkN2Ei9KzUiO4us/EtEKPaMBLoe2c+RSp2ssXL9OXuVAuS3zrkBxeMheDf5VVj6n9ECZdgg7iuA3FttCy9n20ae02mkibAV6jhV5S4jnrT3QxqwWN69tvDz8c5Sq9WUXxT1tzxZyxJ5/o/5SoVubBzQRA+ugzE+3mEQtiyhY4/c9c1lr6gnJtwXgmw==,iv:QyE8Q++C1iITQrD4n+EcfPobRQ4Bw1/6tTLuKda4mIk=,tag:UnReY9YJ9XgtcuzK2pMcmw==,type:str]
            access_key: ENC[AES256_GCM,data:+H6fu2mfOYSUKURKQbxmz54duW0=,iv:/fTrRK+61eQNrCbtg/w56jzhDPYx1EZTyJ1C4mpmyxs=,tag:zY9lDvEordGjbRtBk0z/Gg==,type:str]
            minio_url: ENC[AES256_GCM,data:nW++Lco06SZO5EzgvdX+pDtC,iv:fhzj69tWi6OSqa4oXIlGuWkq/cpXB8U8GOW6pAhvjKA=,tag:NUVJBfasip0B8qzmNjMIWg==,type:str]
            mongo_port: ENC[AES256_GCM,data:ihZCwBk=,iv:zqAjQ+N2izj4Cc794YfYNjaGuGQ3y2o/g9UpuSmckPE=,tag:trhWZ34HUh0aJsM5LIHErg==,type:str]
            mongo_password: ENC[AES256_GCM,data:/+/SXU/5,iv:oxI15nRtbEVkQzSBoIEbhumepOlWg0bwfnzaZqTej+A=,tag:zdojBrUYb2oTC1hO3VuPcg==,type:str]
            bb_url: ENC[AES256_GCM,data:bqrb1LhhUORwI78SjqZmubv/qJr6Jv/JZMDFhIYzHmnL8ViJfA==,iv:KiKYLvIEmvGENu+/7b77ZGIFUOgWV0IfpcbA3aK4f0k=,tag:k2FBL7NXwh72XngwwqurTA==,type:str]
            mongo_database_name: ENC[AES256_GCM,data:dUhtX8G2LUk=,iv:stvij+HHauAtjH33dGVfb4HU79CY8ODNW01LIa0EFBY=,tag:mA/FgRk0ev5RLn7jtewYjA==,type:str]
            flagsmith_environment_key: ENC[AES256_GCM,data:/7B5cip6IxF5ArO4uRLQm+j/CTz9hg==,iv:hMPd5arVzuOA+9P8/nK8tgvBp4FoM941h28Qr2n320A=,tag:HdfzzYUgCXt8YTQjEjQ48A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreHRsT3RpM0JacmIyWTVT
            WmZFN2Q3R1pxSDRiVlpnbG1ockl5OWl5NjJnCmp3UXlxcmg2bFhLWlp2V2t3OXdv
            dzBnMzFpaGhLTUFXS05DQnVWVGpDSkEKLS0tIG9KRkhOVjA3dy9oeHd2RlZ4VlBS
            QUpXVGQxSUZhcEhRRFpHbFl6ZXFkeGMK+WXmxIdWGjmqfdD+ugxlVYR4rcYf4F7n
            3UUqbbDays9kCn5pxH77kicys/vtTO4CrRv8ECc4MokeYj1vNCllQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
    encrypted_suffix: Templates
    lastmodified: "2026-06-09T15:49:32Z"
    mac: ENC[AES256_GCM,data:Od4JPrv0yVSIFP6E/SMM/uk1EhmgpBkq+c7Zwqa9YnrQ8Wd0HKGKiZpE//vn9WwonnGEdAicW7T+0r7bKgm5lUwJzQPf9xiiHcFjiEoyk+uHkqzU4J2Ie98Cv8AF9F9+sZswfiUUKhXfF9xVkV2wpKgrtbcNzwyeme9dMs7OCgk=,iv:1dBaV1Ld3SJaBka3+u5JqrDNxRswePzeJlvE0Ouh/bM=,tag:eBM+94ZVxLtKtYHqYS6hRQ==,type:str]
    version: 3.13.1
