apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minio-secret
    namespace: minio
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:JPTZUZFIBpGDYYVK,iv:c67Oot7EWzC6qR1D93yLkWJHRAily7d6XpcKQBBK0gE=,tag:iSTY3mJ32IvgIZ5l8kIHPA==,type:str]
          stringData:
            clientId: ENC[AES256_GCM,data:FfAP9+ZlfgVHiy5obrS1IZg7c7cv5Z4ihS6NiY46cp/8zrYbIC1VKA==,iv:66OhF8TKTdxhCaRAnLBnvp7DnPbj9l7BsvLC21eGiWQ=,tag:VhSVwfyVu3C3WXbfFCmxMw==,type:str]
            clientSecret: ENC[AES256_GCM,data:ZUrGwOWq3ruyIoAWlrtqZX3mqqVBpWIWSH/uEJT4Nfp/G4Kegs+csXvNvffTZU0ys1O/ZY0G4TCrC95gwilXd3Df6q/DUJmqwZZl8EcpU1X1OWoxozrot989wAVssseFzrRXGoeBtBbNFoU0F193L3azyc7ccKhTPjmYfdjQxb4=,iv:+SDlKXX/e1Jrt7xcVVEQvrbiwGSeLRK1aKUhvDWNiW4=,tag:BfQwbw0OD7ZAIcwCO51r+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOSsxTk9QbEJzRTRQd1Jv
            YnVINFlENWdZejBZQ1FtSkNLdUxrdHR2SEJnClROTlpmMGpqaE43ZUhvb1ZyN2FH
            V1hZZTBCSzM4RDJsdHBnTllwamdMNUUKLS0tIHBqWGErMFpUemRhdlhncFoxeHVr
            UXBqUE1zSFZBYnVBWDI1Y3hNc3Q0eGcKIDoLab1nNzDfqB4rgopv2sYAvyRw0f6I
            U5zDO6gOWXsx+8Gw5r3iPYiBTKN8AImcry0L8vdnjUkyZB2y8ycVeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:09:38Z"
    mac: ENC[AES256_GCM,data:CCxPc66aXbVul6gz/0ZqcefQBReQOdGN3wGwbRTBm1gBlOwSkG50Tn5Pd2dYVKmJMf+QzxzM5IvyntH8w81cvsYZkyEZKgKLcDGQfryZqdjXl14hYWdRp4hkODct1doQP5aSSOXd/Nz2popMuiUNTiZhI6OLDiJ9QfEobX/q78I=,iv:U12+zNL2Iay8XO/KhFbj56vLnH0ZI6Vx4U2CSmMtIAY=,tag:HWAT/ZBstTP85QUvMmuB2Q==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
