apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: webui-secret
    namespace: webui
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:mHvfIFWpDrOAFUHw,iv:YDDozg6Rqu3CTAelufq0uzi+AhKDfRV2OChAQ7B5lTE=,tag:7WW5c9B72ENhhC93M40P/Q==,type:str]
          stringData:
            OAUTH_CLIENT_ID: ENC[AES256_GCM,data:16fCT43RvkQZuKW72mELHlMu5b1o4LoLjsl3cWQUFXe84ufzRtbEBg==,iv:gbIFTfFwnxwvKnnSvz/ibH7Wj5jBljYvVEk9OxPpcSo=,tag:shKleOin6uDYknDRQcJqZw==,type:str]
            OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:f8vIHnFOlDxR5bDyUQTTbbCRe5vPkAMJPAXOqyT4bioL413VRh/7Tkfm8cwSm2BjlJS1hECgfPBuva3dZe+npZkl96hIcVGjsRDRTcPJsNQ88y6I+/tyxuuQsOsdQDAhBZCUyKBgExaovoi2JBLhDX53BaP3Hc84HderkKxUd8M=,iv:OneVS9178Cp85yzsTIj+cwtp2q7zkkhS+vxaXpR0GKw=,tag:IFbH20umq6vazNapGhV1cA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdnYrWlZQMm04dDdzTXUz
            eW5sWkMwbFhOUmx2bGJJbHpVbXo0d3BObTBjCkZPampUdWdUNHRhbmJTRkpLdmxk
            Nnl2MUFEQmYrdWdzS0lUZ2FGbENEcGcKLS0tIE13WHVZdzc2RmVDaGRsR1dIWkFH
            SVJ5VmtrZzZIdDBybE93V0ZOeVRkczgKiATr+/8RVofsDD94oImoTcbiwqHvU34p
            GgmJNLcLthH0UlLvi4K2gmdVpgVs4kkQNZd27QDjnFFkip7I3RToog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:09:38Z"
    mac: ENC[AES256_GCM,data:NB0RKljIqYoi9owsBsQQ8F7xSKgjVRhy3RjmBkuh+ii7rOPgNb/J9Nm/7yX9LckayFZFsbyW1mUkNnLYxgSJ+uv2COyErwXSbn5e+Wi2mljRZA/vH9xOciS+9g+IEqEhAVTjfS2GOluoRaiSfo2Onll1PDbVL9e9PX5aK1TI1BM=,iv:0xPuwHJTt5E7rzhzmct2/A2KmtsfM4ZhTZYLgaa3DaA=,tag:bduMhXfbt+5mQdzja56fuw==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.1
