apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd  # or your Argo CD namespace
spec:
  project: default

  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.17.0 # Check for latest version
    helm: 
      valuesObject: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - ApplyOutOfSyncOnly=true
