apiVersion: v1
kind: Namespace
metadata:
  name: ray-operator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: kuberay-operator
    repoURL: https://ray-project.github.io/kuberay-helm
    targetRevision: 1.1.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ray-operator
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - Replace=true    
      - CreateNamespace=true
